"""
Experiment 1 (data/label audit) + Experiment 8's gate (sequence-length analysis).

Neither needs a GPU or a trained model — they are properties of the data. Running
this first is what makes Experiment 8 answerable: a Longformer is only worth testing
if a substantial amount of text is actually being truncated, and that is a number,
not a guess.

Reports
-------
* Class frequency for y_mc (11-way) and prevalence per multilabel column, split by
  train/val/test, so a split problem shows up as a column that disagrees with its
  neighbours.
* Label co-occurrence — which distortion pairs appear together, and how often. The
  multilabel task is only meaningfully "multi" to the extent this matrix is non-empty.
* Sequence lengths in TOKENS (not words — truncation is a tokenizer property) with
  median / p90 / p95 / p99 / max, and the truncated fraction at each candidate
  --max-length.

Usage
-----
    python -m src.audit_data                          # data/splits, mental-roberta
    python -m src.audit_data --splits data/splits_stage2 --out docs/audit_stage2.md
"""

from __future__ import annotations

import argparse
import itertools
from pathlib import Path

import numpy as np
import pandas as pd

from src.data import DISTORTIONS, MC_CLASSES, TEXT_COL

ML_COLS = [f"ml_{d}" for d in DISTORTIONS]


def _load(splits: Path):
    return {n: pd.read_csv(splits / f"{n}.csv", encoding="utf-8-sig")
            for n in ("train", "val", "test")}


def main(argv=None):
    ap = argparse.ArgumentParser(description="Experiment 1 audit + Experiment 8 length gate.")
    ap.add_argument("--splits", default="data/splits")
    ap.add_argument("--model", default="mental/mental-roberta-base",
                    help="tokenizer used for the length analysis; falls back to "
                         "roberta-base if this one is gated and unavailable offline")
    ap.add_argument("--out", default="docs/audit_data.md")
    args = ap.parse_args(argv)

    d = _load(Path(args.splits))
    L = [f"# Data & label audit — `{args.splits}`\n",
         "Generated by `src/audit_data.py`. No GPU, no model — these are properties of "
         "the data. Covers **Experiment 1** in full and the **Experiment 8** gate.\n"]

    # ---- split sizes -------------------------------------------------------
    L += ["## Split sizes\n", "| split | rows | % |", "|---|---|---|"]
    total = sum(len(x) for x in d.values())
    for n, x in d.items():
        L.append(f"| {n} | {len(x)} | {100 * len(x) / total:.1f}% |")

    # ---- 11-class distribution per split -----------------------------------
    if "y_mc" in d["train"].columns:
        L += ["\n## Multiclass (11-way) distribution\n",
              "A split problem shows up as one column disagreeing with its neighbours.\n",
              "| class | train | % | val | % | test | % |", "|---|---|---|---|---|---|---|"]
        for i, c in enumerate(MC_CLASSES):
            cells = []
            for n in ("train", "val", "test"):
                k = int((d[n].y_mc == i).sum())
                cells.append(f"{k} | {100 * k / len(d[n]):.1f}%")
            L.append(f"| `{c}` | " + " | ".join(cells) + " |")
        counts = d["train"].y_mc.value_counts()
        imb = counts.max() / max(counts.min(), 1)
        L += [f"\n**Imbalance ratio (train, largest:smallest) = {imb:.1f}:1** — "
              f"`{MC_CLASSES[counts.idxmax()]}` {counts.max()} vs "
              f"`{MC_CLASSES[counts.idxmin()]}` {counts.min()}.\n"]

    # ---- multilabel prevalence ---------------------------------------------
    present = [c for c in ML_COLS if c in d["train"].columns]
    if present:
        L += ["\n## Multilabel prevalence\n",
              "| label | train | prevalence | val | test |", "|---|---|---|---|---|"]
        for c in present:
            tr = int(d["train"][c].sum())
            L.append(f"| `{c.replace('ml_', '')}` | {tr} | {100 * tr / len(d['train']):.1f}% | "
                     f"{int(d['val'][c].sum())} | {int(d['test'][c].sum())} |")
        lab = d["train"][present].sum(axis=1)
        L += [f"\nLabels per row (train): mean **{lab.mean():.2f}**, "
              f"max {int(lab.max())}, rows with 0 labels: {int((lab == 0).sum())}, "
              f"with 2+: {int((lab >= 2).sum())} ({100 * (lab >= 2).mean():.1f}%).\n",
              "\nThat last figure is the one that decides whether *multi*-label is the "
              "right framing at all: if almost every row carries a single label, a "
              "multiclass head would model the same thing more directly.\n"]

        # ---- co-occurrence -------------------------------------------------
        L += ["\n## Label co-occurrence (train)\n",
              "Pairs appearing together, most frequent first. Empty or near-empty means "
              "the labels are effectively mutually exclusive.\n",
              "| pair | count |", "|---|---|"]
        pairs = []
        for a, b in itertools.combinations(present, 2):
            k = int(((d["train"][a] == 1) & (d["train"][b] == 1)).sum())
            if k:
                pairs.append((k, a, b))
        for k, a, b in sorted(pairs, reverse=True)[:15]:
            L.append(f"| `{a.replace('ml_', '')}` + `{b.replace('ml_', '')}` | {k} |")
        if not pairs:
            L.append("| *(none — labels are mutually exclusive in train)* | 0 |")

    # ---- Experiment 8: token lengths ---------------------------------------
    L += ["\n## Sequence length — the Experiment 8 gate\n"]
    try:
        from transformers import AutoTokenizer
        try:
            tok = AutoTokenizer.from_pretrained(args.model)
            used = args.model
        except Exception:
            tok = AutoTokenizer.from_pretrained("roberta-base")
            used = "roberta-base (fallback — the requested tokenizer was unavailable)"
        L.append(f"Tokenizer: `{used}`. Lengths include special tokens.\n")
        L += ["| split | median | p90 | p95 | p99 | max |", "|---|---|---|---|---|---|"]
        lens = {}
        for n, x in d.items():
            a = np.array([len(tok.encode(str(t), truncation=False)) for t in x[TEXT_COL]])
            lens[n] = a
            L.append(f"| {n} | {int(np.median(a))} | {int(np.percentile(a, 90))} | "
                     f"{int(np.percentile(a, 95))} | {int(np.percentile(a, 99))} | {int(a.max())} |")
        L += ["\n### Truncated fraction by `--max-length`\n",
              "| max_length | train | val | test |", "|---|---|---|---|"]
        for m in (128, 256, 512):
            row = " | ".join(f"{100 * (lens[n] > m).mean():.1f}%" for n in ("train", "val", "test"))
            L.append(f"| {m} | {row} |")
        t512 = 100 * (lens["test"] > 512).mean()
        L += [f"\n**Verdict at 512 tokens: {t512:.1f}% of test rows are truncated.** ",
              "A long-context model is only worth the cost if this is substantial — "
              "the standard reading is that a few percent does not justify Longformer, "
              "since the truncated tail is mostly short overruns rather than lost "
              "content. Judge it against the p95 column above, not the max.\n"]
    except Exception as e:      # pragma: no cover
        L.append(f"*Length analysis unavailable: {e}*\n")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(L), encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
